theme = "hugo-icon"
baseURL = "https://www.example.com/"
languageCode = "en-US"
title = "Rune"

# Metadata
[params]
  author = "Rune"
  description = "The Rune CMS"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"

# Navigation section
[params.nav]
  mission = "Our Mission"
  services = "Technology"
  team = "The Team"
  careers = "Careers"
  # Include logo instead if HOME:
  logo = "/images/rune.svg"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "scalability"
    title = "Scalability"
    subtitle = "Unlike monolithic Content Management Systems, Rune is easily scalable thanks to Kubernetes."
    description = "<p>We don't want our users to worry about their systems or operations. Rune offers a set-it-and-forget-it solution. As your website grows, so will your installation.</p><ul class='checked'><li>Automatic scaling w/ Kubernetes</li></ul>"

  [[params.mission.item]]
    weight = 3
    name = "speed"
    title = "Speed"
    subtitle = "News websites are some of the slowest to load. With Rune, we want to bring news to the 21st century."
    description = "<p>We're focused on making sure our websites are as fast as possible. A single news article should not take 8 seconds to load.</p><ul class='checked'><li>Dynamic content w/ Polymer</li><li>Fast service communication w/ gRPC</li></ul>"

  [[params.mission.item]]
    weight = 2
    name = "powerful"
    title = "Powerful"
    subtitle = ""
    description = "<p>Rune is the first CMS to move at the pace of the newsroom. Bring all of your content into one place and publish faster than ever.</p><ul class='checked'><li>Curate visually appealing content fast</li><li><Publish across multiple sites with ease</li></ul>"

# Services section
[params.services]
  enable = true
  video = false
  vidlink = ""
  title = "Features"
  description = "The features supported by the Rune CMS"

  [[params.services.item]]
    icon = "fa fa-clone"
    title = "Multi-site"
    description = "Multi-site support with sharable content"

  [[params.services.item]]
    icon = "fa fa-paper-plane"
    title = "Fast"
    description = "Thanks to Go and gRPC, Rune is the fastest CMS on the market"

  [[params.services.item]]
    icon = "fa fa-pencil"
    title = "Rich Editing"
    description = "Our home-grown content creation interface provides users with a rich user experience"

  [[params.services.item]]
    icon = "fa fa-users"
    title = "Subscription management"
    description = "Manage digital subscriptions & accept recurring payments from within Rune"

  [[params.services.item]]
    icon = "fa fa-support"
    title = "Customer Support"
    description = "Manage basic customer support features from within Rune, or create webhooks for external services"

  [[params.services.item]]
    icon = "fa fa-code-fork"
    title = "Open Source"
    description = "We want to give back to the community that has given so much. Rune would not be possible without open source software."


# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "The Rune Team"
  description = ""

  [[params.team.item]]
    name = "Mat"
    position = "Project Manager"
    description = ""
    img = "images/person1.jpg"
    twitter = "https://twitter.com/mwcosta"

  [[params.team.item]]
    name = "Jason"
    position = "Developer"
    description = ""
    img = "images/person2.jpg"
    twitter = "https://twitter.com/zikes"
    github = "http://github.com/zikes"

  [[params.team.item]]
    name = "Michael"
    position = "Developer"
    description = ""
    img = "images/person3.jpg"
    twitter = "https://twitter.com/@michaelcale"
    github = "https://github.com/michaelcale"

  [[params.team.item]]
    name = "Kevin"
    position = "Developer"
    description = ""
    img = "images/person3.jpg"
    twitter = "https://twitter.com/klminehart"
    github = "http://github.com/kminehart"

# Careers section
[params.careers]
  enable = true
  title = "We're hiring"
  description = "<div>Send resumes, cover letters, and an optional portfolio to jobs@wehco.com</div>"

  [[params.careers.item]]
  title = "Front-end developer"
  description = "The front-end developer role is primarily responsible for designing and developing front-end assets."
  requirements = '<ul><li>Keen eye for design</li><li>Reasonable understanding of JavaScript</li></ul><h4>Bonus points</h4><ul><li>React</li><li>Polymer</li><li>Typescript, Dart, or Kotlin</li><li>Docker</li></ul>'

# Contact section
[params.contact]
  enable = false
  title = "Get In Touch"
  message = "Let us know if you have any questions, or if you have any interest in participating in the Rune CMS project"


# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2017 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a><br>The Rune CMS and runecms.io are products of <a href='http://wehco.com/'>WEHCO Media</a></small></p>"
  github = "#"
  twitter = "#"
  facebook = "#"
  vine = "#"
  linkedin = "#"
  instagram = "#"

